# Generated by Django 4.1.3 on 2022-11-25 15:19

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
