# Generated by Django 4.1.3 on 2022-11-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE_Site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('bird_audi_file', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='BirdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('bird_image_file', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='new_model',
        ),
    ]
