# Generated by Django 4.1.3 on 2022-11-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE_Site', '0002_birdaudio_birdimage_delete_new_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('bird_file', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='BirdAudio',
        ),
        migrations.DeleteModel(
            name='BirdImage',
        ),
    ]
