# Generated by Django 4.1.3 on 2022-11-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE_Site', '0004_birdimage_delete_birdfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='birdimage',
            name='bird_image_location',
            field=models.FileField(upload_to='media/images'),
        ),
    ]
