# Generated by Django 4.1.3 on 2022-11-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE_Site', '0006_delete_birdaudio_alter_birdimage_bird_image_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird_audio_location', models.FileField(upload_to='media/')),
            ],
        ),
    ]
