# Generated by Django 4.1.3 on 2022-11-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE_Site', '0008_alter_birdimage_bird_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdaudio',
            name='bird_audio_location',
            field=models.FileField(upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='birdimage',
            name='bird_image_location',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
